package com.Lilith.Curtain.utils;

import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.util.Map;

import com.Lilith.Curtain.CurtainRules;
import com.Lilith.Curtain.api.rules.CurtainRule;
import com.Lilith.Curtain.api.rules.RuleManager;

/**
 * Development helper: writes docs/RULES.md from the declared rules. Run it with
 * {@code ./gradlew generateRulesReadme}.
 */
public class CurtainRulesGenerator {

    private static final String HEADER = "# CURTAIN RULES (generated by CurtainRulesGenerator, do not edit by hand)\n"
        + "\n"
        + "> 1.7.10 port. Rules that depend on content which does not exist in 1.7.10 are not part of this list:\n"
        + "> stackableShulkerBoxes, emptyShulkerBoxStackAlways, scaffoldingDistance, turtleEggTrampledDisabled\n"
        + "> and betterWoodStrip. creativeNoClip uses Entity#noClip (1.7.10 has no spectator mode) and\n"
        + "> fillUpdates is inert (no /fill, /clone, /setblock or structure blocks). See docs/PORTING.md.\n"
        + "\n"
        + "* Add Features\n";

    public CurtainRulesGenerator() {}

    public static void main(String[] args) {
        RuleManager.addRules(CurtainRules.class);
        setTrans();
        String language = args.length > 0 ? args[0] : "zh_cn";
        CurtainRules.language = language;

        StringBuilder sb = new StringBuilder(HEADER);
        for (Map.Entry<String, CurtainRule<?>> entry : RuleManager.RULES.entrySet()) {
            CurtainRule<?> rule = entry.getValue();
            sb.append("    * ")
                .append(entry.getKey())
                .append("\n");
            sb.append("        * 名称：`")
                .append(TranslationHelper.translateLiteral(rule.getNameTranslationKey()))
                .append("`\n");
            sb.append("        * 描述：`")
                .append(TranslationHelper.translateLiteral(rule.getDescTranslationKey()))
                .append("`\n");
            sb.append("        * 类型：`")
                .append(getTypeString(rule.getType()))
                .append("`\n");
            sb.append("        * 默认：`")
                .append(rule.getDefaultValue())
                .append("`\n");
            StringBuilder suggestion = new StringBuilder();
            for (String s : rule.getSuggestions()) suggestion.append("`")
                .append(s)
                .append("`, ");
            String str = suggestion.toString();
            if (str.length() >= 2) {
                sb.append("        * 建议：")
                    .append(str, 0, str.length() - 2)
                    .append("\n");
            }
            StringBuilder category = new StringBuilder();
            for (String s : rule.getCategories()) {
                category.append("`")
                    .append(TranslationHelper.translateLiteral(String.format("%s.categories.%s", "curtain", s)))
                    .append("`, ");
            }
            str = category.toString();
            if (str.length() >= 2) {
                sb.append("        * 分类：")
                    .append(str, 0, str.length() - 2)
                    .append("\n");
            }
        }
        try (FileWriter fileWriter = new FileWriter("docs/RULES.md")) {
            fileWriter.write("");
            fileWriter.write(sb.toString());
            fileWriter.flush();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    private static void setTrans() {
        InputStream stream = TranslationHelper.class.getClassLoader()
            .getResourceAsStream("assets/curtain/lang/zh_cn.json");
        TranslationHelper.addTransMap("zh_cn", TranslationHelper.getTranslationFromResourcePath(stream));
        stream = TranslationHelper.class.getClassLoader()
            .getResourceAsStream("assets/curtain/lang/en_us.json");
        TranslationHelper.addTransMap("en_us", TranslationHelper.getTranslationFromResourcePath(stream));
    }

    private static String getTypeString(Class<?> clazz) {
        if (clazz == Boolean.TYPE || clazz == Boolean.class) return "Boolean";
        if (clazz == Integer.TYPE || clazz == Integer.class) return "Integer";
        if (clazz == String.class) return "String";
        if (clazz == Double.TYPE || clazz == Double.class) return "Double";
        return clazz.getSimpleName();
    }
}
